notifications:
  email:
    on_success: always
    on_failure: always
  slack: srboeingdotnet:pZz5KfrgntyjLpS9a1d2b1rH
mono: none
script:
  - dig TXT +short o-o.myaddr.l.google.com @ns1.google.com | awk -F'"' '{ print $2}'       
  - ifconfig     
  - chmod +x ./deploy.sh
after_success: 
  - /bin/bash ./deploy.sh

